/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertyAnalysisRouteImport } from './routes/property-analysis'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as ApiNeighborhoodScoreRouteImport } from './routes/api/neighborhood-score'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PropertyAnalysisRoute = PropertyAnalysisRouteImport.update({
  id: '/property-analysis',
  path: '/property-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNeighborhoodScoreRoute = ApiNeighborhoodScoreRouteImport.update({
  id: '/api/neighborhood-score',
  path: '/api/neighborhood-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/property-analysis': typeof PropertyAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/neighborhood-score': typeof ApiNeighborhoodScoreRoute
  '/areas/$slug': typeof AreasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/property-analysis': typeof PropertyAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/neighborhood-score': typeof ApiNeighborhoodScoreRoute
  '/areas/$slug': typeof AreasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/property-analysis': typeof PropertyAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/neighborhood-score': typeof ApiNeighborhoodScoreRoute
  '/areas/$slug': typeof AreasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/compare'
    | '/property-analysis'
    | '/api/chat'
    | '/api/neighborhood-score'
    | '/areas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/compare'
    | '/property-analysis'
    | '/api/chat'
    | '/api/neighborhood-score'
    | '/areas/$slug'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/compare'
    | '/property-analysis'
    | '/api/chat'
    | '/api/neighborhood-score'
    | '/areas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompareRoute: typeof CompareRoute
  PropertyAnalysisRoute: typeof PropertyAnalysisRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiNeighborhoodScoreRoute: typeof ApiNeighborhoodScoreRoute
  AreasSlugRoute: typeof AreasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/property-analysis': {
      id: '/property-analysis'
      path: '/property-analysis'
      fullPath: '/property-analysis'
      preLoaderRoute: typeof PropertyAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/neighborhood-score': {
      id: '/api/neighborhood-score'
      path: '/api/neighborhood-score'
      fullPath: '/api/neighborhood-score'
      preLoaderRoute: typeof ApiNeighborhoodScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompareRoute: CompareRoute,
  PropertyAnalysisRoute: PropertyAnalysisRoute,
  ApiChatRoute: ApiChatRoute,
  ApiNeighborhoodScoreRoute: ApiNeighborhoodScoreRoute,
  AreasSlugRoute: AreasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
